### ISSUE TITLE
Observer(观察者)模式 | Summary Of work

### ISSUE THREAD

**Issue by Banny-Gao** [Banny-Gao/mackkkk.github.io.comments#24]
https://mackkkk.github.io/bookReading/JavascriptDesign/9.html 

 The description of the site.

**Comment by tangpingl** [comment]
大神 代码太优雅了，大神请教下 hello world 怎么写？react怎么快速入门呢？最近想学习前端

**Comment by Banny-Gao** [comment]
> @tangpingl
> 大神 代码太优雅了，大神请教下 hello world 怎么写？react怎么快速入门呢？最近想学习前端 

唐总，别搞Java了。转前端吧，java太上脑细胞了

**Comment by tpxiang** [comment]
大佬，请问下Vue2.x跟Vue3.0的区别是什么呢？可否解读下Vue3.0的源码？
